### PR TITLE
Added cancel method to recognition .h .m

### PR DESCRIPTION
**Pull request by haup0002**
attempting to add cancel functionality to the plugin.

### CODE REVIEW

**Comment by macdonst** [comment]
@haup0002 so does cancel ever work for you with these changes? Or even with the changes cancel still does not work?

**Comment by haup0002** [comment]
Still does not work with the changes unfortunately.

**Comment by macdonst** [comment]
@haup0002 crap, sorry I did not see your answer sooner. I believe it to be because the cancel is called on a separate instance of the speech rec engine.

**Comment by macdonst** [comment]
@haup0002 I'm not going to merge this PR as it has been superseded by ba1b3e467445482eaca692a7836c108476b9451e. The JS methods are `abort` and `cancel` so those are what I added into the iOS code. In order for the cordova bridge to find the right method signature you'd need to include `CDVInvokedUrlCommand` to your method.

Also, as I suspected we needed to init the speech rec engine earlier and use the same instance in the abort/cancel methods.

**Pull request closed without merging**
